PackageIdentifier: NVIDIA.App
PackageVersion: 1.0.16.0
InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://us.download.nvidia.com/nvapp/client/11.0.5.420/NVIDIA_app_v11.0.5.420.exe
  InstallerSha256: a5283562cd12cd94d28fc373c2d805054e626c29a2f33831936df6671200ab01
ManifestType: installer
ManifestVersion: 1.4.0
