PackageIdentifier: NVIDIA.App
PackageVersion: 0.0.0.1
InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://login.microsoftonline.com/43083d15-7273-40c1-b7db-39efd9ccc17a/oauth2/v2.0/authorize?client_id=ea7a59bf-4742-4921-af21-a6038c499e1f&nonce=LIX1ySkTSL1jXbiRTZ69GZZ-saxko4YD92tyqQmxmpQ%3D&redirect_uri=https%3A%2F%2Fnvidia-be.glean.com%2Fauthorization-code%2Fcallback&response_mode=query&response_type=code&scope=openid+profile+email+offline_access&state=8VSdLr1q_qXsNLQMNru-4CcppaaIyShIeDAbHnMu0Go%3D
  InstallerSha256: 727bab4e5004de68b63a19c8f4880c1737a2daf55f7758980df6c37164f653c7
ManifestType: installer
ManifestVersion: 1.4.0
