PackageIdentifier: NVIDIA.App
PackageVersion: 0.0.0.1
InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://login.microsoftonline.com/43083d15-7273-40c1-b7db-39efd9ccc17a/oauth2/v2.0/authorize?client_id=ea7a59bf-4742-4921-af21-a6038c499e1f&nonce=G1IzGm-K9z7Cv34IG2-gZ_jGni3p4JrzhMA861-5qKA%3D&redirect_uri=https%3A%2F%2Fnvidia-be.glean.com%2Fauthorization-code%2Fcallback&response_mode=query&response_type=code&scope=openid+profile+email+offline_access&state=d4usOLKLf8SP0TGN8KmyAZqlAF3Sh8srUQiAV2CgsHc%3D
  InstallerSha256: 02c02be3fe926da49ceb407f19dfa21f93d7a83e3d78834b4f616e37c8de9fa1
ManifestType: installer
ManifestVersion: 1.4.0
